package org.tain.cxf.filetransfer.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2018-09-11T23:49:48.638+09:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://fileTransfer.cxf.tain.org/", name = "UploadServiceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface UploadServiceImpl {

    @WebMethod
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://fileTransfer.cxf.tain.org/", className = "org.tain.cxf.filetransfer.client.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://fileTransfer.cxf.tain.org/", className = "org.tain.cxf.filetransfer.client.UploadFileResponse")
    public void uploadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        org.tain.cxf.filetransfer.client.FileUploader arg0
    );
}
