
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tain.cxf.filetransfer.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2018-09-11T23:49:48.611+09:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "UploadServiceImplService",
                      portName = "UploadServiceImplPort",
                      targetNamespace = "http://fileTransfer.cxf.tain.org/",
                      wsdlLocation = "http://localhost:8080/CxfFileTransfer01/services/UploadServiceImplPort?wsdl",
                      endpointInterface = "org.tain.cxf.filetransfer.client.UploadServiceImpl")
                      
public class UploadServiceImplPortImpl implements UploadServiceImpl {

    private static final Logger LOG = Logger.getLogger(UploadServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tain.cxf.filetransfer.client.UploadServiceImpl#uploadFile(org.tain.cxf.filetransfer.client.FileUploader  arg0 )*
     */
    public void uploadFile(org.tain.cxf.filetransfer.client.FileUploader arg0) { 
        LOG.info("Executing operation uploadFile");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
