
package org.tain.cxf.filetransfer.provider.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Tue Sep 11 23:56:14 KST 2018
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "uploadFileResponse", namespace = "http://provider.filetransfer.cxf.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uploadFileResponse", namespace = "http://provider.filetransfer.cxf.tain.org/")

public class UploadFileResponse {


}

