
package org.tain.cxf.filetrans.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Wed Sep 12 01:18:09 KST 2018
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "uploadResponse", namespace = "http://filetrans.cxf.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uploadResponse", namespace = "http://filetrans.cxf.tain.org/")

public class UploadResponse {


}

