
package org.tain.cxf.filetrans.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.7
 * Thu Sep 13 00:54:29 KST 2018
 * Generated source version: 2.2.7
 */

@XmlRootElement(name = "uploadResponse", namespace = "http://filetrans.cxf.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uploadResponse", namespace = "http://filetrans.cxf.tain.org/")

public class UploadResponse {


}

