package org.tain.cxf.filetransfer.consumer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Wed Sep 12 17:41:29 KST 2018
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://provider.filetransfer.cxf.tain.org/", name = "FileTransferImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface FileTransferImpl {

    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://provider.filetransfer.cxf.tain.org/", className = "org.tain.cxf.filetransfer.consumer.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://provider.filetransfer.cxf.tain.org/", className = "org.tain.cxf.filetransfer.consumer.UploadResponse")
    public void upload(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1
    );

    @WebMethod
    @RequestWrapper(localName = "download", targetNamespace = "http://provider.filetransfer.cxf.tain.org/", className = "org.tain.cxf.filetransfer.consumer.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://provider.filetransfer.cxf.tain.org/", className = "org.tain.cxf.filetransfer.consumer.DownloadResponse")
    @WebResult(name = "return", targetNamespace = "")
    public byte[] download(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
