
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tain.cxf.filetransfer.consumer;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Wed Sep 12 17:41:29 KST 2018
 * Generated source version: 2.2.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "FileTransferImplService",
                      portName = "FileTransferImplPort",
                      targetNamespace = "http://provider.filetransfer.cxf.tain.org/",
                      wsdlLocation = "http://localhost:8080/CxfProFileTrans02/services/FileTransferImplPort?wsdl",
                      endpointInterface = "org.tain.cxf.filetransfer.consumer.FileTransferImpl")
                      
public class FileTransferImplImpl implements FileTransferImpl {

    private static final Logger LOG = Logger.getLogger(FileTransferImplImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tain.cxf.filetransfer.consumer.FileTransferImpl#upload(java.lang.String  arg0 ,)byte[]  arg1 )*
     */
    public void upload(java.lang.String arg0,byte[] arg1) { 
        LOG.info("Executing operation upload");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tain.cxf.filetransfer.consumer.FileTransferImpl#download(java.lang.String  arg0 )*
     */
    public byte[] download(java.lang.String arg0) { 
        LOG.info("Executing operation download");
        System.out.println(arg0);
        try {
            byte[] _return = new byte[] {};
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
