
/*
 * 
 */

package org.tain.cxf.filetransfer.consumer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.7
 * Wed Sep 12 17:41:29 KST 2018
 * Generated source version: 2.2.7
 * 
 */


@WebServiceClient(name = "FileTransferImplService", 
                  wsdlLocation = "http://localhost:8080/CxfProFileTrans02/services/FileTransferImplPort?wsdl",
                  targetNamespace = "http://provider.filetransfer.cxf.tain.org/") 
public class FileTransferImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://provider.filetransfer.cxf.tain.org/", "FileTransferImplService");
    public final static QName FileTransferImplPort = new QName("http://provider.filetransfer.cxf.tain.org/", "FileTransferImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CxfProFileTrans02/services/FileTransferImplPort?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8080/CxfProFileTrans02/services/FileTransferImplPort?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public FileTransferImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FileTransferImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileTransferImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns FileTransferImpl
     */
    @WebEndpoint(name = "FileTransferImplPort")
    public FileTransferImpl getFileTransferImplPort() {
        return super.getPort(FileTransferImplPort, FileTransferImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileTransferImpl
     */
    @WebEndpoint(name = "FileTransferImplPort")
    public FileTransferImpl getFileTransferImplPort(WebServiceFeature... features) {
        return super.getPort(FileTransferImplPort, FileTransferImpl.class, features);
    }

}
