
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.tain.cxf.filetrans;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2018-09-13T00:56:51.815+09:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "FileTransferImplService",
                      portName = "FileTransferImplPort",
                      targetNamespace = "http://filetrans.cxf.tain.org/",
                      wsdlLocation = "http://localhost:8080/CxfProFileTrans01/services/FileTransferImplPort?wsdl",
                      endpointInterface = "org.tain.cxf.filetrans.FileTransferImpl")
                      
public class FileTransferImplPortImpl implements FileTransferImpl {

    private static final Logger LOG = Logger.getLogger(FileTransferImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.tain.cxf.filetrans.FileTransferImpl#upload(java.lang.String  arg0 ,)byte[]  arg1 )*
     */
    public void upload(java.lang.String arg0,byte[] arg1) { 
        LOG.info("Executing operation upload");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.tain.cxf.filetrans.FileTransferImpl#download(java.lang.String  arg0 )*
     */
    public byte[] download(java.lang.String arg0) { 
        LOG.info("Executing operation download");
        System.out.println(arg0);
        try {
            byte[] _return = new byte[] {};
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
