
package org.tain.cxf.filetransfer.provider.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.7
 * Wed Sep 12 17:34:15 KST 2018
 * Generated source version: 2.2.7
 */

@XmlRootElement(name = "downloadResponse", namespace = "http://provider.filetransfer.cxf.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "downloadResponse", namespace = "http://provider.filetransfer.cxf.tain.org/")

public class DownloadResponse {

    @XmlElement(name = "return")
    private byte[] _return;

    public byte[] getReturn() {
        return this._return;
    }

    public void setReturn(byte[] new_return)  {
        this._return = new_return;
    }

}

