package hanwha.neo.branch.common.transferfile.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue Sep 18 15:52:09 KST 2018
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://ws.transferfile.common.branch.neo.hanwha/", name = "TransferFileService")
@XmlSeeAlso({ObjectFactory.class})
public interface TransferFileService {

    @WebMethod
    @RequestWrapper(localName = "download", targetNamespace = "http://ws.transferfile.common.branch.neo.hanwha/", className = "hanwha.neo.branch.common.transferfile.ws.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://ws.transferfile.common.branch.neo.hanwha/", className = "hanwha.neo.branch.common.transferfile.ws.DownloadResponse")
    @WebResult(name = "return", targetNamespace = "")
    public hanwha.neo.branch.common.transferfile.ws.TransferFile download(
        @WebParam(name = "FILE_PATH", targetNamespace = "")
        java.lang.String filePATH
    );

    @WebMethod
    @RequestWrapper(localName = "upload", targetNamespace = "http://ws.transferfile.common.branch.neo.hanwha/", className = "hanwha.neo.branch.common.transferfile.ws.Upload")
    @ResponseWrapper(localName = "uploadResponse", targetNamespace = "http://ws.transferfile.common.branch.neo.hanwha/", className = "hanwha.neo.branch.common.transferfile.ws.UploadResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String upload(
        @WebParam(name = "TRANSFER_FILE", targetNamespace = "")
        hanwha.neo.branch.common.transferfile.ws.TransferFile transferFILE
    );
}
