
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package hanwha.neo.branch.common.transferfile.ws;

import java.util.logging.Logger;

import javax.activation.DataHandler;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue Sep 18 15:52:09 KST 2018
 * Generated source version: 2.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "TransferFileServiceImplService",
                      portName = "TransferFileServiceImplPort",
                      targetNamespace = "http://ws.transferfile.common.branch.neo.hanwha/",
                      wsdlLocation = "http://hanwha.eagleoffice.co.kr/neo/ws/common/transferFile?wsdl",
                      endpointInterface = "hanwha.neo.branch.common.transferfile.ws.TransferFileService")

public class TransferFileServiceImpl implements TransferFileService {

    private static final Logger LOG = Logger.getLogger(TransferFileServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see hanwha.neo.branch.common.transferfile.ws.TransferFileService#download(java.lang.String  filePATH )*
     */
    public hanwha.neo.branch.common.transferfile.ws.TransferFile download(java.lang.String filePATH) {
        LOG.info("Executing operation download");
        System.out.println(filePATH);
        try {
            hanwha.neo.branch.common.transferfile.ws.TransferFile _return = new hanwha.neo.branch.common.transferfile.ws.TransferFile();
            DataHandler _returnDataHandler = null; //new DataHandler();
            _return.setDataHandler(_returnDataHandler);
            _return.setFileName("FileName-1048412930");
            _return.setFilePath("FilePath281342950");
            _return.setFileSize("FileSize1641955092");
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see hanwha.neo.branch.common.transferfile.ws.TransferFileService#upload(hanwha.neo.branch.common.transferfile.ws.TransferFile  transferFILE )*
     */
    public java.lang.String upload(hanwha.neo.branch.common.transferfile.ws.TransferFile transferFILE) {
        LOG.info("Executing operation upload");
        System.out.println(transferFILE);
        try {
            java.lang.String _return = "_return-1783077261";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
