
package hanwha.neo.branch.common.transferfile.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.activation.DataHandler;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue Sep 18 15:52:09 KST 2018
 * Generated source version: 2.2.7
 *
 */

public final class TransferFileService_TransferFileServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.transferfile.common.branch.neo.hanwha/", "TransferFileServiceImplService");

    private TransferFileService_TransferFileServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TransferFileServiceImplService.WSDL_LOCATION;
        if (args.length > 0) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TransferFileServiceImplService ss = new TransferFileServiceImplService(wsdlURL, SERVICE_NAME);
        TransferFileService port = ss.getTransferFileServiceImplPort();

        {
        System.out.println("Invoking download...");
        java.lang.String _download_filePATH = "_download_filePATH1207686399";
        hanwha.neo.branch.common.transferfile.ws.TransferFile _download__return = port.download(_download_filePATH);
        System.out.println("download.result=" + _download__return);


        }
        {
        System.out.println("Invoking upload...");
        hanwha.neo.branch.common.transferfile.ws.TransferFile _upload_transferFILE = new hanwha.neo.branch.common.transferfile.ws.TransferFile();
        DataHandler _upload_transferFILEDataHandler = null; //new byte[] {};
        _upload_transferFILE.setDataHandler(_upload_transferFILEDataHandler);
        _upload_transferFILE.setFileName("FileName-855845295");
        _upload_transferFILE.setFilePath("FilePath2142989635");
        _upload_transferFILE.setFileSize("FileSize1913757058");
        java.lang.String _upload__return = port.upload(_upload_transferFILE);
        System.out.println("upload.result=" + _upload__return);


        }

        System.exit(0);
    }

}
