
package org.tain.cxf.filetransfer.consumer;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2018-09-11T23:58:55.294+09:00
 * Generated source version: 3.0.1
 * 
 */
public final class UploadServiceImpl_UploadServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://provider.filetransfer.cxf.tain.org/", "UploadServiceImplService");

    private UploadServiceImpl_UploadServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UploadServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UploadServiceImplService ss = new UploadServiceImplService(wsdlURL, SERVICE_NAME);
        UploadServiceImpl port = ss.getUploadServiceImplPort();  
        
        {
        System.out.println("Invoking uploadFile...");
        org.tain.cxf.filetransfer.consumer.FileUploader _uploadFile_arg0 = new org.tain.cxf.filetransfer.consumer.FileUploader();
        _uploadFile_arg0.setFileType("FileType-1140511244");
        byte[] _uploadFile_arg0Handler = new byte[] {};
        _uploadFile_arg0.setHandler(_uploadFile_arg0Handler);
        _uploadFile_arg0.setName("Name-1198332274");
        port.uploadFile(_uploadFile_arg0);


        }

        System.exit(0);
    }

}
