package org.tain.cxf.filetransfer.consumer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2018-09-11T23:58:55.372+09:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "UploadServiceImplService", 
                  wsdlLocation = "http://localhost:8080/CxfFileTransfer02/services/UploadServiceImplPort?wsdl",
                  targetNamespace = "http://provider.filetransfer.cxf.tain.org/") 
public class UploadServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://provider.filetransfer.cxf.tain.org/", "UploadServiceImplService");
    public final static QName UploadServiceImplPort = new QName("http://provider.filetransfer.cxf.tain.org/", "UploadServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CxfFileTransfer02/services/UploadServiceImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UploadServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CxfFileTransfer02/services/UploadServiceImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UploadServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UploadServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UploadServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UploadServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UploadServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns UploadServiceImpl
     */
    @WebEndpoint(name = "UploadServiceImplPort")
    public UploadServiceImpl getUploadServiceImplPort() {
        return super.getPort(UploadServiceImplPort, UploadServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadServiceImpl
     */
    @WebEndpoint(name = "UploadServiceImplPort")
    public UploadServiceImpl getUploadServiceImplPort(WebServiceFeature... features) {
        return super.getPort(UploadServiceImplPort, UploadServiceImpl.class, features);
    }

}
