
package org.tain.cxf.filetransfer.provider.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Wed Sep 12 18:01:35 KST 2018
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "upload", namespace = "http://provider.filetransfer.cxf.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "upload", namespace = "http://provider.filetransfer.cxf.tain.org/", propOrder = {"arg0", "arg1"})

public class Upload {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;
    @XmlElement(name = "arg1")
    private byte[] arg1;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

    public byte[] getArg1() {
        return this.arg1;
    }

    public void setArg1(byte[] newArg1)  {
        this.arg1 = newArg1;
    }

}

