
package org.tain.cxf.fileTransfer.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.1
 * Tue Sep 11 23:43:32 KST 2018
 * Generated source version: 3.0.1
 */

@XmlRootElement(name = "uploadFile", namespace = "http://fileTransfer.cxf.tain.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uploadFile", namespace = "http://fileTransfer.cxf.tain.org/")

public class UploadFile {

    @XmlElement(name = "arg0")
    private org.tain.cxf.fileTransfer.FileUploader arg0;

    public org.tain.cxf.fileTransfer.FileUploader getArg0() {
        return this.arg0;
    }

    public void setArg0(org.tain.cxf.fileTransfer.FileUploader newArg0)  {
        this.arg0 = newArg0;
    }

}

